/**
 * Daily Plan Memory Storage
 * 
 * Manages persistence of daily plans generated by the planner engine.
 */

const fs = require('fs').promises;
const path = require('path');

const MEMORY_DIR = path.join(__dirname);
const DAILY_PLAN_DIR = path.join(MEMORY_DIR, 'daily-plan');

/**
 * Normalizes tasks to ensure they have taskNumber and completed fields
 * @param {Array} tasks - Array of task objects
 * @param {number} startNumber - Starting task number (default: 1)
 * @returns {Array} Normalized tasks with taskNumber and completed fields
 */
function normalizeTasks(tasks, startNumber = 1) {
  if (!Array.isArray(tasks)) {
    return [];
  }

  return tasks.map((task, index) => {
    // Ensure task is an object
    if (!task || typeof task !== 'object') {
      return null;
    }

    return {
      ...task,
      taskNumber: task.taskNumber || (startNumber + index),
      completed: task.completed !== undefined ? task.completed : false
    };
  }).filter(Boolean); // Remove any null entries
}

/**
 * Normalizes an entire plan to ensure all tasks have required fields
 * @param {Object} plan - Daily plan object
 * @returns {Object} Normalized plan with all tasks properly structured
 */
function normalizePlan(plan) {
  if (!plan || typeof plan !== 'object') {
    return plan;
  }

  // Normalize focusTasks and otherTasks
  const focusTasks = normalizeTasks(plan.focusTasks || [], 1);
  
  // Calculate starting number for otherTasks (after focus tasks)
  const otherTasksStart = focusTasks.length + 1;
  const otherTasks = normalizeTasks(plan.otherTasks || [], otherTasksStart);

  return {
    ...plan,
    focusTasks,
    otherTasks,
    metadata: {
      ...(plan.metadata || {}),
      totalTasks: focusTasks.length + otherTasks.length,
      normalizedAt: new Date().toISOString()
    }
  };
}

/**
 * Ensures a directory exists, creates it if necessary
 * @param {string} dirPath - Directory path to ensure
 */
async function ensureDirectory(dirPath) {
  try {
    await fs.access(dirPath);
  } catch {
    await fs.mkdir(dirPath, { recursive: true });
  }
}

/**
 * Saves a daily plan to persistent storage
 * @param {string} dateStr - Date in YYYY-MM-DD format
 * @param {Object} plan - Daily plan object
 * @returns {Promise<void>}
 */
async function saveDailyPlan(dateStr, plan) {
  // Validate date format
  if (!/^\d{4}-\d{2}-\d{2}$/.test(dateStr)) {
    throw new Error('Invalid date format: expected YYYY-MM-DD');
  }

  // Validate plan object
  if (!plan || typeof plan !== 'object') {
    throw new Error('Invalid plan: must be an object');
  }

  try {
    // Ensure the daily-plan directory exists
    await ensureDirectory(DAILY_PLAN_DIR);

    // Normalize the plan before saving (ensures taskNumber and completed fields)
    const normalizedPlan = normalizePlan(plan);

    const filePath = path.join(DAILY_PLAN_DIR, `${dateStr}.json`);

    // Write normalized plan with pretty formatting
    await fs.writeFile(filePath, JSON.stringify(normalizedPlan, null, 2), 'utf-8');

    console.log(`[DailyPlanMemory] Saved daily plan for ${dateStr}`);
    console.log(`[DailyPlanMemory] Focus tasks: ${normalizedPlan.focusTasks?.length || 0}, Other tasks: ${normalizedPlan.otherTasks?.length || 0}`);

  } catch (error) {
    console.error(`[DailyPlanMemory] Error saving plan for ${dateStr}:`, error.message);
    throw error;
  }
}

/**
 * Loads a daily plan from persistent storage
 * @param {string} dateStr - Date in YYYY-MM-DD format
 * @returns {Promise<Object|null>} Daily plan object or null if not found
 */
async function loadDailyPlan(dateStr) {
  // Validate date format
  if (!/^\d{4}-\d{2}-\d{2}$/.test(dateStr)) {
    throw new Error('Invalid date format: expected YYYY-MM-DD');
  }

  const filePath = path.join(DAILY_PLAN_DIR, `${dateStr}.json`);

  try {
    const fileContent = await fs.readFile(filePath, 'utf-8');
    const plan = JSON.parse(fileContent);

    // Normalize the plan after loading (auto-corrects old JSON files)
    const normalizedPlan = normalizePlan(plan);

    console.log(`[DailyPlanMemory] Loaded daily plan for ${dateStr}`);
    console.log(`[DailyPlanMemory] Focus tasks: ${normalizedPlan.focusTasks?.length || 0}, Total tasks: ${normalizedPlan.metadata?.totalTasks || 0}`);

    // Save the normalized plan back to disk if fields were added
    const hasChanges = JSON.stringify(plan) !== JSON.stringify(normalizedPlan);
    if (hasChanges) {
      console.log(`[DailyPlanMemory] Auto-correcting missing fields in ${dateStr}.json`);
      await fs.writeFile(filePath, JSON.stringify(normalizedPlan, null, 2), 'utf-8');
    }

    return normalizedPlan;

  } catch (error) {
    if (error.code === 'ENOENT') {
      // File doesn't exist
      console.log(`[DailyPlanMemory] No daily plan found for ${dateStr}`);
      return null;
    }

    // Other errors (parse error, read error, etc.)
    console.error(`[DailyPlanMemory] Error loading plan for ${dateStr}:`, error.message);
    throw error;
  }
}

/**
 * Gets the absolute file path for a daily plan
 * @param {string} dateStr - Date in YYYY-MM-DD format
 * @returns {string} Absolute path to the daily plan file
 */
function getDailyPlanPath(dateStr) {
  // Validate date format
  if (!/^\d{4}-\d{2}-\d{2}$/.test(dateStr)) {
    throw new Error('Invalid date format: expected YYYY-MM-DD');
  }

  return path.join(DAILY_PLAN_DIR, `${dateStr}.json`);
}

module.exports = {
  saveDailyPlan,
  loadDailyPlan,
  getDailyPlanPath,
  normalizeTasks,
  normalizePlan
};
